### ISSUE TITLE
Need confirmation to keep working

### ISSUE THREAD

**Issue by vivgui** [pyladies/pyladies-theme#1]
Hey @econchick, can you take a look at the new theme?

**Comment by econchick** [comment]
Hey @viviangb - I _really_ like it; the front page looks amazing.  I filled some issues - not sure if all of them are "doable" but whatever is possible is great.  Overall it looks super clean and I think you did a really great job.

Since this isn't a part of the theme but more of the content itself, I may go in and change around the templates (e.g. having something `<h2>` instead of `<h3>` or something).

Hope this helps.  Please definitely keep progressing if you have more ideas.  Whenever you're ready, I can put this up on a testing site so we can get the other chapter leaders' input.

**Comment by vivgui** [comment]
@econchick All right, I saw the issues and hopefully I'll have them fixed by this weekend. Thanks a lot for helping out!
